### ISSUE TITLE
Tethers don't connect immediately after double jumping

### ISSUE THREAD

**Issue by O1yyy** [HDR-Development/HewDraw-Remix#1934]
Basically, this:

https://github.com/HDR-Development/HewDraw-Remix/assets/19886440/5200c701-dd00-4871-bb71-d44e1190db65

the only inputs being done are Y + Z, makes trying to recover close with tether a pain because it will simply not connect

more video footage: 

https://cdn.discordapp.com/attachments/660221136042328113/1147133593425027152/2023090103470500-0E7DF678130F4F0FA2C88AE72B47AFDF.mp4

**Comment by moklmaru** [comment]
Cannot replicate on most recent nightly. Tethers will properly connect to ledge immediately after a double jump, tested on multiple characters

The interaction in the provided videos will still occur due to the lockout of regrabbing the ledge. But it isn't related to double jumping and shouldn't get in the way of recovery
