### ISSUE TITLE
Nana Moonwalk Slide Jank

### ISSUE THREAD

**Issue by WoodrowManuel** [HDR-Development/HewDraw-Remix#216]
By moonwalking out of a dashdance, nana slides very far in the direction the moonwalk sends you. I'll attach a video in the troubleshooting channel later once I figure out sysdvr.

**Comment by WoodrowManuel** [comment]
https://streamable.com/u3zuez

Decided to just drop the example here for the sake of convenience. Pardon the visual bugging, still working on figuring out sysdvr. 
In regards to the nana slide, it just seems to happen when you dashdance in general, but can be triggered earlier than usual by moonwalking out of a dashdance.

**Comment by techyCoder81** [comment]
nana has historically been desynced by dash dances. this was changed in ult since they have a dashback status, but we've removed that. So now she is still desynced by dash dance. This looks like the kind of emergent behavior that will be so deeply ingrained in a massive inaccessible status script, or even main, that it probably isnt workable at this time
