### ISSUE TITLE
Pac-Man's up air cannot be fastfalled

### ISSUE THREAD

**Issue by kalomaze** [HDR-Development/HewDraw-Remix#301]
Holding down the control stick while inputting pacman up air will not result in a fast falled aerial. All of his other aerials can be fast falled / SHFF'd.

**Comment by black-calculus** [comment]
This is due to the animation shifting him upwards, which removes the condition for being able to fast fall the move (having nonpositive vertical velocity) until towards the halfway point of the move. Extremely hesitant to address this as that property is extremely important for platform setups for the move and many Pac-Man mains I know make use of that property to their benefit.
