### ISSUE TITLE
Nightly v33 is broken on Ryujinx

### ISSUE THREAD

**Issue by zandm7** [HDR-Development/HewDraw-Remix#331]
Emulator crashes upon loading in to a match/training. Nightly v30 does not have this issue, so #326 or #329 should be the culprit.

**Comment by BedeScarlet** [comment]
[Ryujinx_1.0.0-dirty_2022-03-18_22-55-04.log](https://github.com/HDR-Development/HewDraw-Remix/files/8308482/Ryujinx_1.0.0-dirty_2022-03-18_22-55-04.log)
At the end of this log is the error that results from the crash. the middle stuff is just shader stuff obv
I do suspect #/326 since it changes a lot of files

**Comment by zandm7** [comment]
Seems like this has been fixed as of nightly v34, closing
