### ISSUE TITLE
While falling down, Robin's up b 1 doesn't grab ledge when it should

### ISSUE THREAD

**Issue by blu-dev** [HDR-Development/HewDraw-Remix#468]
Repro:
1. Pick robin
2. Pick a stage with a ledge
3. Hang from ledge and drop down, up b close enough to ledge that you go over without snapping on land
4. Robin doesn't snap

**Comment by techyCoder81** [comment]
This move additionally can be canceled in two ways - shield cancel and only doing the first hit. The shield cancel should be removed, since you can already just only do the first up special. Additionally, up special could be adjusted to behave like two charges, where if you only do the first one, you are still able to do the first part a second time later during the same airtime.

**Comment by gitgotgud** [comment]
this issue has been fixed. tested and wasn't able to find anything wrong with the robin's ledgesnapping
