### ISSUE TITLE
Ganon DACUS/DACDS Change

### ISSUE THREAD

**Issue by TTPain** [HDR-Development/HewDraw-Remix#488]
After the change to the universal 7 frame dacus input Ganon's dash attack cancel moves are pretty much useless, moving his dash attack up a few frames or shifting those 7 frames about 3 frames later would allow him to get some much needed burst movement.

**Comment by blu-dev** [comment]
The issues should primarily be used for reporting bugs, or by the developers/contributors when writing things that were discussed in depth. If you have a link to such a discussion for this issue, please provide it here, otherwise I'm closing this and leaving it as wontfix because we decided a while ago that not every character needs a good DACUS.
