### ISSUE TITLE
Pokemon Trainer crashes HDR when switching between Pokemon

### ISSUE THREAD

**Issue by MaTaTaX999** [HDR-Development/HewDraw-Remix#868]
1. I initially thought it would crash on stage with transformation if you switch during a transition but I found later that was not the case. Seems to happen randomly as far as I have seen. Smash simply freezes (if online on both ends) and Smash has to be closed from the home menu and reopened to play again.
2. Both online and offline this is an issue
3. Latest switch version but this has been like this (as far as I've noticed) since I started playing a few months ago. A bit before the tournament skin pack came out. I never had an issue with the emulators crashing when using PT.
4. Stock battle, 4 socks, 8 mins

My SD card is formatted to FAT32 and I have not tried a fresh install as I am not the one who modded my switch. This issue has happened on at least 3 other switches when playing offline.

**Comment by Jetsplit** [comment]
I also am getting this, but I'm using the Character Expansion mod to have the PT Pokémon separated. So, they can't and aren't switching with Down B, but the game is randomly crashing (freeze for awhile then the software aborts) when they're about to touch the blastzone (so right before they would switch if they weren't separated).

Not sure if that still indicates the problem is with them switching, or if the problem is just with the Pokémon in general, or if my issue's different from yours. I've gotten it with each of the 3 Pokémon.
