### ISSUE TITLE
Salty Runback + Pokemon Switch crashes the game

### ISSUE THREAD

**Issue by zer0lif3** [HDR-Development/HewDraw-Remix#992]
After loading a game with salty runback, switching pokemon with pokemon trainer will crash the game. I've seen people mention that switching pokemon in general crashes the game but I've only ever seen it happen after salty runback is used.

**Comment by Riah321** [comment]
Holy shit has it finally been solved?

**Comment by Jetsplit** [comment]
I'm sorry to say this because I'd really like a solution for this issue, but I can say with 100% certainty I've experienced the crash without using salty runback. :(

In my case, I didn't reload a match using salty runback, but I do have the PT Pokémon separated using the Character Expansion Mod. Without any match being reloaded with salty runback since the Switch was last powered on, the game crashed when Trainer-less Squirtle was about to hit the blastzone. This does not happen every time one of the Pokémon is about to hit the blastzone, just sometimes.

That said, it's entirely possible there's a separate issue when using the separated Pokémon, and the Trainer itself won't crash if salty runback isn't used. That would require further testing from someone who doesn't have the Pokémon separated.
